# Python Libraries 1

_September 16, 2020_ 

Agenda today:
- Introduction to Numpy: array math
- Introduction to Pandas: importing, indexing, and math

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /Users/Khyatee/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: python-dateutil>=2 in /Users/Khyatee/anaconda3/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in /Users/Khyatee/anaconda3/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: numpy>=1.7.0 in /Users/Khyatee/anaconda3/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /Users/Khyatee/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2->pandas)
You are using pip version 9.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Part I. Numpy
The basic data structure that exist in numpy is called numpy arrays. NP arrays are very similar to python lists. The __difference__ between a python list and a Numpy array is that list can only a mix of data types but array can only contain the same data type.

But what is the benefits of using NumPy array instead of the base python lists?
- Speed 
- Broadcasting Property

In [3]:
names_list=['Bob','John','Sally']
names_array=np.char.array(['Bob','John','Sally']) #use numpy.array for numbers and numpy.char.array for strings
print(names_list)
print(names_array)

['Bob', 'John', 'Sally']
['Bob' 'John' 'Sally']

In [4]:
import time

size_of_seq = 100000

def pure_python_version():
    tic = time.time()
    X = range(size_of_seq)
    Y = range(size_of_seq)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    toc = time.time()
    return toc - tic

def numpy_version():
    tic = time.time()
    X = np.arange(size_of_seq)
    Y = np.arange(size_of_seq)
    Z = X + Y 
    toc = time.time()
    return toc - tic


t1 = pure_python_version()
t2 = numpy_version()
print("python: " + str(t1), "numpy: "+ str(t2))
print("Numpy is in this example " + str(t1/t2) + " times faster!")

python: 0.07747125625610352 numpy: 0.00162506103515625
Numpy is in this example 47.672828638497656 times faster!

In [5]:
## broadcasting and array math

np.array([2,3,4,6]) * 5

array([10, 15, 20, 30])

In [6]:
li = [2,3,4,6]
li * 5

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]

In [7]:
## simulation with numpy - in normal distribution 
rand = np.random.randn(100000);
plt.hist(rand, bins = 200);

There are many other wonderous things numpy can do, you will encounter them later in the course of the program.

## Part II. Pandas
Pandas stand for paneled data, and it is the most popular library for data scientists to manipulate, clean, and organize dataset in Python. The most fundamental data structure that exists in Pandas is called **DataFrames**.

In [9]:
## importing data and look at optional parameters
df = pd.read_csv('auto-mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [10]:
# examine and read the data

In [11]:
# examine the information in this dataframe

In [12]:
# examine the datatypes of the dataframe

In [13]:
# talk about series and dataframe 
type(df)

pandas.core.frame.DataFrame

In [14]:
# series

In [15]:
# indexing and subsetting 

# index by values

In [17]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [18]:
df.loc[2,'horsepower']

'150'

In [19]:
df.iloc[4, 8]

'ford torino'

In [21]:
df.iloc[4:6, :6]

    mpg  cylinders  displacement horsepower  weight  acceleration
4  17.0          8         302.0        140    3449          10.5
5  15.0          8         429.0        198    4341          10.0

In [23]:
# want weight greater than 3000
df[df['weight'] >3000]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
34,16.0,6,225.0,105,3439,15.5,71,1,plymouth satellite custom
35,17.0,6,250.0,100,3329,15.5,71,1,chevrolet chevelle malibu
36,19.0,6,250.0,88,3302,15.5,71,1,ford torino 500
37,18.0,6,232.0,100,3288,15.5,71,1,amc matador
38,14.0,8,350.0,165,4209,12.0,71,1,chevrolet impala
39,14.0,8,400.0,175,4464,11.5,71,1,pontiac catalina brougham
40,14.0,8,351.0,153,4154,13.5,71,1,ford galaxie 500
41,14.0,8,318.0,150,4096,13.0,71,1,plymouth fury iii
42,12.0,8,383.0,180,4955,11.5,71,1,dodge monaco (sw)
43,13.0,8,400.0,170,4746,12.0,71,1,ford country squire (sw)
44,13.0,8,400.0,175,5140,12.0,71,1,pontiac safari (sw)
47,19.0,6,250.0,100,3282,15.0,71,1,pontiac firebird
...,...,...,...,...,...,...,...,...,...
264,18.1,8,302.0,139,3205,11.2,78,1,ford futura
265,17.5,8,318.0,140,4080,13.7,78,1,dodge magnum xe
275,17.0,6,163.0,125,3140,13.6,78,2,volvo 264gl
277,16.2,6,163.0,133,3410,15.8,78,2,peugeot 604sl
280,21.5,6,231.0,115,3245,15.4,79,1,pontiac lemans v6
283,20.2,6,232.0,90,3265,18.2,79,1,amc concord dl 6
284,20.6,6,225.0,110,3360,16.6,79,1,dodge aspen 6
285,17.0,8,305.0,130,3840,15.4,79,1,chevrolet caprice classic
286,17.6,8,302.0,129,3725,13.4,79,1,ford ltd landau
287,16.5,8,351.0,138,3955,13.2,79,1,mercury grand marquis
288,18.2,8,318.0,135,3830,15.2,79,1,dodge st. regis
289,16.9,8,350.0,155,4360,14.9,79,1,buick estate wagon (sw)
290,15.5,8,351.0,142,4054,14.3,79,1,ford country squire (sw)
291,19.2,8,267.0,125,3605,15.0,79,1,chevrolet malibu classic (sw)
292,18.5,8,360.0,150,3940,13.0,79,1,chrysler lebaron town @ country (sw)
297,25.4,5,183.0,77,3530,20.1,79,2,mercedes benz 300d
298,23.0,8,350.0,125,3900,17.4,79,1,cadillac eldorado
299,27.2,4,141.0,71,3190,24.8,79,2,peugeot 504
300,23.9,8,260.0,90,3420,22.2,79,1,oldsmobile cutlass salon brougham
315,24.3,4,151.0,90,3003,20.1,80,1,amc concord
316,19.1,6,225.0,90,3381,18.7,80,1,dodge aspen
328,30.0,4,146.0,67,3250,21.8,80,2,mercedes-benz 240d
359,28.1,4,141.0,80,3230,20.4,81,2,peugeot 505s turbo diesel
360,30.7,6,145.0,76,3160,19.6,81,2,volvo diesel
363,22.4,6,231.0,110,3415,15.8,81,1,buick century
364,26.6,8,350.0,105,3725,19.0,81,1,oldsmobile cutlass ls
365,20.2,6,200.0,88,3060,17.1,81,1,ford granada gl
366,17.6,6,225.0,85,3465,16.6,81,1,chrysler lebaron salon
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl
387,38.0,6,262.0,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)

In [24]:
# examine whether we have missing value - it could really affect the data!
df.isnull().sum().any()

False

In [27]:
# exercise - want weight greater than 3000 and mpg less than 18 
df[(df.weight > 3000) & (df.mpg <18)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
34,16.0,6,225.0,105,3439,15.5,71,1,plymouth satellite custom
35,17.0,6,250.0,100,3329,15.5,71,1,chevrolet chevelle malibu
38,14.0,8,350.0,165,4209,12.0,71,1,chevrolet impala
39,14.0,8,400.0,175,4464,11.5,71,1,pontiac catalina brougham
40,14.0,8,351.0,153,4154,13.5,71,1,ford galaxie 500
41,14.0,8,318.0,150,4096,13.0,71,1,plymouth fury iii
42,12.0,8,383.0,180,4955,11.5,71,1,dodge monaco (sw)
43,13.0,8,400.0,170,4746,12.0,71,1,ford country squire (sw)
44,13.0,8,400.0,175,5140,12.0,71,1,pontiac safari (sw)
62,13.0,8,350.0,165,4274,12.0,72,1,chevrolet impala
63,14.0,8,400.0,175,4385,12.0,72,1,pontiac catalina
64,15.0,8,318.0,150,4135,13.5,72,1,plymouth fury iii
65,14.0,8,351.0,153,4129,13.0,72,1,ford galaxie 500
66,17.0,8,304.0,150,3672,11.5,72,1,amc ambassador sst
...,...,...,...,...,...,...,...,...,...
187,17.5,8,305.0,140,4215,13.0,76,1,chevrolet chevelle malibu classic
188,16.0,8,318.0,150,4190,13.0,76,1,dodge coronet brougham
189,15.5,8,304.0,120,3962,13.9,76,1,amc matador
190,14.5,8,351.0,152,4215,12.8,76,1,ford gran torino
202,17.5,6,258.0,95,3193,17.8,76,1,amc pacer d/l
208,13.0,8,318.0,150,3940,13.2,76,1,plymouth volare premier v8
211,16.5,6,168.0,120,3820,16.7,76,2,mercedes-benz 280s
212,16.5,8,350.0,180,4380,12.1,76,1,cadillac seville
213,13.0,8,350.0,145,4055,12.0,76,1,chevy c10
214,13.0,8,302.0,130,3870,15.0,76,1,ford f108
215,13.0,8,318.0,150,3755,14.0,76,1,dodge d100
221,17.5,8,305.0,145,3880,12.5,77,1,chevrolet caprice classic
222,17.0,8,260.0,110,4060,19.0,77,1,oldsmobile cutlass supreme
223,15.5,8,318.0,145,4140,13.7,77,1,dodge monaco brougham
224,15.0,8,302.0,130,4295,14.9,77,1,mercury cougar brougham
225,17.5,6,250.0,110,3520,16.4,77,1,chevrolet concours
229,16.0,8,400.0,180,4220,11.1,77,1,pontiac grand prix lj
230,15.5,8,350.0,170,4165,11.4,77,1,chevrolet monte carlo landau
231,15.5,8,400.0,190,4325,12.2,77,1,chrysler cordoba
232,16.0,8,351.0,149,4335,14.5,77,1,ford thunderbird
263,17.7,6,231.0,165,3445,13.4,78,1,buick regal sport coupe (turbo)
265,17.5,8,318.0,140,4080,13.7,78,1,dodge magnum xe
275,17.0,6,163.0,125,3140,13.6,78,2,volvo 264gl
277,16.2,6,163.0,133,3410,15.8,78,2,peugeot 604sl
285,17.0,8,305.0,130,3840,15.4,79,1,chevrolet caprice classic
286,17.6,8,302.0,129,3725,13.4,79,1,ford ltd landau
287,16.5,8,351.0,138,3955,13.2,79,1,mercury grand marquis
289,16.9,8,350.0,155,4360,14.9,79,1,buick estate wagon (sw)
290,15.5,8,351.0,142,4054,14.3,79,1,ford country squire (sw)
366,17.6,6,225.0,85,3465,16.6,81,1,chrysler lebaron salon

In [38]:
# exercise - get the cars that are heavier than 3000 but has a horsepower less than 150 

df.loc[374,'horsepower']
df.drop(index = 374)
# df['horsepower'] = df['horsepower'].astype(int)
# df[(df.weight >3000) & (df.horsepower <150)]
# should be 150 cars that satisfy the criteria

TypeError: drop() got an unexpected keyword argument 'index'

In [ ]:
# seems like we have a problem! Can we try to debug this?

In [ ]:
# get rid of anomaly

In [ ]:
# exercise - get a list of car name where the mpg is less than 18 and weight is greater than 3500